### ISSUE TITLE
Still Alive?

### ISSUE THREAD

**Issue by furesoft** [F1uctus/Axion#32]
Is this project still alive? I love the idea of language orientatet programming. I am the developer of backlang and I want to make axion a full robsu language that can be compiled to il, like backlang does.

**Comment by F1uctus** [comment]
I do return to this project to tinker on some idea, or to upgrade the deps, but no great ideas have been here in the meantime.
In case you really want to do development in this repository, I've moved the repo into the org and added you as a maintainer.
